name = "glyph-server"
main = "src/index.ts"
compatibility_date = "2025-06-07"

[[kv_namespaces]]
binding = "VAULT_STORE"
id = "4249da843d634f3fb70246c944e49c12"

[vars]
CORS_ORIGIN = "https://glyph.pages.dev"

[observability]
enabled = true
